### ISSUE TITLE
Need some information

### ISSUE THREAD

**Issue by theodorosploumis** [kbariotis/KBariotis_Linkwise#1]
What kind of integration does it offer? 
Is there a Linkwise API available?

Does this export the products of the store to an xml? Or it is used to report sales from customers on Linkwise?

I was building a [linkwise module](https://github.com/theodorosploumis/linkwise) for a Drupal project and found yours.

**Comment by kbariotis** [comment]
@theodorosploumis this integrates the Linkwise's script to your Magento store. No XML exporting or directly communication with Linkwise.

Not sure if there is an API though.
